version: "3"

services:
  commodity:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-commodity.properties:/app/application.properties
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20


  javanode-outcome:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-outcomenode.properties:/app/application.properties
      - ./data:/data
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  javanode1:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-datanode1.properties:/app/application.properties
      - ./data:/data
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  javanode2:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-datanode2.properties:/app/application.properties
      - ./data:/data
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  pythonnode1:
    build: ../
    volumes:
      - ../python:/app
      - ./data:/data
    command: >
      poetry run python -m verticox.datanode --data-path /data/features_0.parquet 
      --commodity-address 
      commodity --address pythonnode1 --include-column event_happened


  pythonnode2:
    build: ../
    volumes:
      - ../python:/app
      - ./data:/data
    command: >
      poetry run python -m verticox.datanode --data-path /data/features_1.parquet 
      --commodity-address 
      commodity --address pythonnode2 --include-column event_happened

  aggregator:
    build: ../
    volumes:
      - ../python:/app
      - ./data:/data
    command: >
      poetry run python tests/test_mock.py train /data/outcome.parquet /data event_time 
      event_happened
    depends_on:
      commodity:
        condition: service_healthy
    environment:
      - LOGLEVEL=INFO
