version: "3"

services:
  commodity:
    image: openjdk
    volumes:
      - ${PWD}/$JARFILE:/app/application.jar
      - ${PWD}/src/main/resources/application-commodity.properties:/app/application.properties
      - ${PWD}/resources/smallK2Example_firsthalf.csv:/data/data.csv
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties
    ports:
      - "8080:80"

  datanode1:
    image: openjdk
    volumes:
      - ${PWD}/$JARFILE:/app/application.jar
      - ${PWD}/src/main/resources/application-datanode1.properties:/app/application.properties
      - ${PWD}/resources/smallK2Example_secondhalf.csv:/data/data.csv
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  datanode2:
    image: openjdk
    volumes:
      - ${PWD}/$JARFILE:/app/application.jar
      - ${PWD}/src/main/resources/application-datanode2.properties:/app/application.properties
      - ${PWD}/resources/smallK2Example_thirdhalf.csv:/data/data.csv
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  pythonnode:
    image: continuumio/miniconda3
