version: "3"

services:
  commodity:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-commodity.properties:/app/application.properties
      - ${PWD}/data/outcome.parquet:/data/data.parquet
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties
    ports:
      - "8080:80"
#    healthcheck:
#      test: [ "CMD", "curl", "http://localhost" ]
#      interval: 5s
#      timeout: 5s
#      retries: 20


  javanode-outcome:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-outcomenode.properties:/app/application.properties
      - ${PWD}/data/outcome.parquet:/data/data.parquet
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  javanode1:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-datanode1.properties:/app/application.properties
      - ${PWD}/data/data_1.parquet:/data/data.parquet
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  javanode2:
    image: openjdk
    volumes:
      - $JARFILE:/app/application.jar
      - ${PWD}/application-datanode2.properties:/app/application.properties
      - ${PWD}/data/data_2.parquet:/data/data.parquet
    working_dir: /app
    command: java -jar ./application.jar -DPROP_FILE=application.properties

  pythonnode1:
    build: ../
    volumes:
      - ../python:/app
      - ./data/data_1.parquet:/data/data.parquet
    command: >
      poetry run python -m verticox.datanode --data-path /data/data.parquet --commodity-address 
      commodity --address pythonnode1 --include-column event_happened


  pythonnode2:
    build: ../
    volumes:
      - ../python:/app
      - ./data/data_2.parquet:/data/data.parquet
    command: >
      poetry run python -m verticox.datanode --data-path /data/data.parquet --commodity-address 
      commodity --address pythonnode2 --include-column event_happened

  aggregator:
    build: ../
    volumes:
      - ../python:/app
      - ./data/outcome.parquet:/data/data.parquet
    command: >
      poetry run python tests/test_local_node_manager.py /data/data.parquet event_time event_happened
    depends_on:
      commodity:
        condition: service_healthy
    restart: on-failure

