site_name: Verticox+ docs
theme:
  name: material
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [python]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js