# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verticox/grpc/datanode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cverticox/grpc/datanode.proto\"?\n\x14\x41ggregatedParameters\x12\r\n\x05gamma\x18\x01 \x03(\x02\x12\r\n\x05sigma\x18\x02 \x03(\x02\x12\t\n\x01z\x18\x03 \x03(\x02\"/\n\x0fLocalParameters\x12\r\n\x05gamma\x18\x01 \x03(\x02\x12\r\n\x05sigma\x18\x02 \x03(\x02\"\"\n\x0bNumFeatures\x12\x13\n\x0bnumFeatures\x18\x01 \x01(\x05\" \n\nNumSamples\x12\x12\n\nnumSamples\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xd6\x01\n\x08\x44\x61taNode\x12!\n\x03\x66it\x12\x06.Empty\x1a\x10.LocalParameters\"\x00\x12(\n\x0egetNumFeatures\x12\x06.Empty\x1a\x0c.NumFeatures\"\x00\x12&\n\rgetNumSamples\x12\x06.Empty\x1a\x0b.NumSamples\"\x00\x12\x33\n\x10updateParameters\x12\x15.AggregatedParameters\x1a\x06.Empty\"\x00\x12 \n\x0c\x63omputeGamma\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')



_AGGREGATEDPARAMETERS = DESCRIPTOR.message_types_by_name['AggregatedParameters']
_LOCALPARAMETERS = DESCRIPTOR.message_types_by_name['LocalParameters']
_NUMFEATURES = DESCRIPTOR.message_types_by_name['NumFeatures']
_NUMSAMPLES = DESCRIPTOR.message_types_by_name['NumSamples']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
AggregatedParameters = _reflection.GeneratedProtocolMessageType('AggregatedParameters', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEDPARAMETERS,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:AggregatedParameters)
  })
_sym_db.RegisterMessage(AggregatedParameters)

LocalParameters = _reflection.GeneratedProtocolMessageType('LocalParameters', (_message.Message,), {
  'DESCRIPTOR' : _LOCALPARAMETERS,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:LocalParameters)
  })
_sym_db.RegisterMessage(LocalParameters)

NumFeatures = _reflection.GeneratedProtocolMessageType('NumFeatures', (_message.Message,), {
  'DESCRIPTOR' : _NUMFEATURES,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:NumFeatures)
  })
_sym_db.RegisterMessage(NumFeatures)

NumSamples = _reflection.GeneratedProtocolMessageType('NumSamples', (_message.Message,), {
  'DESCRIPTOR' : _NUMSAMPLES,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:NumSamples)
  })
_sym_db.RegisterMessage(NumSamples)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_DATANODE = DESCRIPTOR.services_by_name['DataNode']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGGREGATEDPARAMETERS._serialized_start=32
  _AGGREGATEDPARAMETERS._serialized_end=95
  _LOCALPARAMETERS._serialized_start=97
  _LOCALPARAMETERS._serialized_end=144
  _NUMFEATURES._serialized_start=146
  _NUMFEATURES._serialized_end=180
  _NUMSAMPLES._serialized_start=182
  _NUMSAMPLES._serialized_end=214
  _EMPTY._serialized_start=216
  _EMPTY._serialized_end=223
  _DATANODE._serialized_start=226
  _DATANODE._serialized_end=440
# @@protoc_insertion_point(module_scope)
