# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verticox/grpc/datanode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cverticox/grpc/datanode.proto\"D\n\rInitialValues\x12\r\n\x05gamma\x18\x01 \x01(\x02\x12\t\n\x01z\x18\x02 \x01(\x02\x12\x0c\n\x04\x62\x65ta\x18\x03 \x01(\x02\x12\x0b\n\x03rho\x18\x04 \x01(\x02\"?\n\x14\x41ggregatedParameters\x12\r\n\x05gamma\x18\x01 \x03(\x02\x12\r\n\x05sigma\x18\x02 \x03(\x02\x12\t\n\x01z\x18\x03 \x03(\x02\"/\n\x0fLocalParameters\x12\r\n\x05gamma\x18\x01 \x03(\x02\x12\r\n\x05sigma\x18\x02 \x03(\x02\"\"\n\x0bNumFeatures\x12\x13\n\x0bnumFeatures\x18\x01 \x01(\x05\" \n\nNumSamples\x12\x12\n\nnumSamples\x18\x01 \x01(\x05\"\x14\n\x04\x42\x65ta\x12\x0c\n\x04\x62\x65ta\x18\x01 \x03(\x02\"\x1d\n\x0c\x46\x65\x61tureNames\x12\r\n\x05names\x18\x01 \x03(\t\"?\n\nDHExchange\x12\x0e\n\x06paramP\x18\x01 \x01(\x05\x12\x0e\n\x06paramG\x18\x02 \x01(\x05\x12\x11\n\tpublicKey\x18\x03 \x01(\x0c\"\x1a\n\tPublicKey\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty2\x88\x03\n\x08\x44\x61taNode\x12!\n\x03\x66it\x12\x06.Empty\x1a\x10.LocalParameters\"\x00\x12(\n\x0egetNumFeatures\x12\x06.Empty\x1a\x0c.NumFeatures\"\x00\x12&\n\rgetNumSamples\x12\x06.Empty\x1a\x0b.NumSamples\"\x00\x12\x33\n\x10updateParameters\x12\x15.AggregatedParameters\x1a\x06.Empty\"\x00\x12 \n\x0c\x63omputeGamma\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1a\n\x07getBeta\x12\x06.Empty\x1a\x05.Beta\"\x00\x12#\n\x07prepare\x12\x0e.InitialValues\x1a\x06.Empty\"\x00\x12\x18\n\x04kill\x12\x06.Empty\x1a\x06.Empty\"\x00\x12*\n\x0fgetFeatureNames\x12\x06.Empty\x1a\r.FeatureNames\"\x00\x12)\n\x0c\x65xchangeKeys\x12\x0b.DHExchange\x1a\n.PublicKey\"\x00\x62\x06proto3')



_INITIALVALUES = DESCRIPTOR.message_types_by_name['InitialValues']
_AGGREGATEDPARAMETERS = DESCRIPTOR.message_types_by_name['AggregatedParameters']
_LOCALPARAMETERS = DESCRIPTOR.message_types_by_name['LocalParameters']
_NUMFEATURES = DESCRIPTOR.message_types_by_name['NumFeatures']
_NUMSAMPLES = DESCRIPTOR.message_types_by_name['NumSamples']
_BETA = DESCRIPTOR.message_types_by_name['Beta']
_FEATURENAMES = DESCRIPTOR.message_types_by_name['FeatureNames']
_DHEXCHANGE = DESCRIPTOR.message_types_by_name['DHExchange']
_PUBLICKEY = DESCRIPTOR.message_types_by_name['PublicKey']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
InitialValues = _reflection.GeneratedProtocolMessageType('InitialValues', (_message.Message,), {
  'DESCRIPTOR' : _INITIALVALUES,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:InitialValues)
  })
_sym_db.RegisterMessage(InitialValues)

AggregatedParameters = _reflection.GeneratedProtocolMessageType('AggregatedParameters', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEDPARAMETERS,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:AggregatedParameters)
  })
_sym_db.RegisterMessage(AggregatedParameters)

LocalParameters = _reflection.GeneratedProtocolMessageType('LocalParameters', (_message.Message,), {
  'DESCRIPTOR' : _LOCALPARAMETERS,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:LocalParameters)
  })
_sym_db.RegisterMessage(LocalParameters)

NumFeatures = _reflection.GeneratedProtocolMessageType('NumFeatures', (_message.Message,), {
  'DESCRIPTOR' : _NUMFEATURES,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:NumFeatures)
  })
_sym_db.RegisterMessage(NumFeatures)

NumSamples = _reflection.GeneratedProtocolMessageType('NumSamples', (_message.Message,), {
  'DESCRIPTOR' : _NUMSAMPLES,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:NumSamples)
  })
_sym_db.RegisterMessage(NumSamples)

Beta = _reflection.GeneratedProtocolMessageType('Beta', (_message.Message,), {
  'DESCRIPTOR' : _BETA,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:Beta)
  })
_sym_db.RegisterMessage(Beta)

FeatureNames = _reflection.GeneratedProtocolMessageType('FeatureNames', (_message.Message,), {
  'DESCRIPTOR' : _FEATURENAMES,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:FeatureNames)
  })
_sym_db.RegisterMessage(FeatureNames)

DHExchange = _reflection.GeneratedProtocolMessageType('DHExchange', (_message.Message,), {
  'DESCRIPTOR' : _DHEXCHANGE,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:DHExchange)
  })
_sym_db.RegisterMessage(DHExchange)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEY,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:PublicKey)
  })
_sym_db.RegisterMessage(PublicKey)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'verticox.grpc.datanode_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_DATANODE = DESCRIPTOR.services_by_name['DataNode']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIALVALUES._serialized_start=32
  _INITIALVALUES._serialized_end=100
  _AGGREGATEDPARAMETERS._serialized_start=102
  _AGGREGATEDPARAMETERS._serialized_end=165
  _LOCALPARAMETERS._serialized_start=167
  _LOCALPARAMETERS._serialized_end=214
  _NUMFEATURES._serialized_start=216
  _NUMFEATURES._serialized_end=250
  _NUMSAMPLES._serialized_start=252
  _NUMSAMPLES._serialized_end=284
  _BETA._serialized_start=286
  _BETA._serialized_end=306
  _FEATURENAMES._serialized_start=308
  _FEATURENAMES._serialized_end=337
  _DHEXCHANGE._serialized_start=339
  _DHEXCHANGE._serialized_end=402
  _PUBLICKEY._serialized_start=404
  _PUBLICKEY._serialized_end=430
  _EMPTY._serialized_start=432
  _EMPTY._serialized_end=439
  _DATANODE._serialized_start=442
  _DATANODE._serialized_end=834
# @@protoc_insertion_point(module_scope)
