name: Build java package
on:
  workflow_call:
  push:
    branches:
      - 185-build-is-failing
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jarfile: ${{steps.jarpath.outputs}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: gitBot
          server-password: ${{ secrets.MAVEN_TOKEN }}
      - name: Check settings
        run: cat ~/.m2/settings.xml
      - name: Build
        working-directory: java/verticox
        run: |
          mvn --settings  ~/.m2/settings.xml clean package
          ls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get jar file path"
        working-directory: java/verticox/target
        id: "jarfile"
        run: echo JARFILE=$(ls -1 |grep -e ".jar$"|head|sed -e "s/[\t]*//") >> $GITHUB_OUTPUT
      - name: Print jarfile
        run: echo ${{ steps.jarfile.outputs.JARFILE }}
      - name: "Upload jar file as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: jarfile
          path: "java/verticox/target/${{ steps.jarfile.outputs.JARFILE }}"

