name: Build java package
on:
  workflow_call:
defaults:
  run:
    working-directory: java
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jarfile: ${{steps.jarpath.outputs}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build

        run: mvn --settings settings.xml package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get jar file path"
        id: "jarfile"
        run: echo JARFILE=$(ls -1 target|grep .jar|head|sed -e "s/[\t]*//") >> $GITHUB_OUTPUT
      - name: Print jarfile
        run: echo ${{ steps.jarfile.outputs.JARFILE }}
      - name: "Upload jar file as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: jarfile
          path: "target/${{ steps.jarfile.outputs.JARFILE }}"

