name: Build java package
on:
  workflow_call:

jobs:
  build:
    env:
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      GITBOT: gitBot
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      jarfile: ${{steps.jarpath.outputs}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: GITBOT
          server-password: MAVEN_TOKEN
      - name: Check settings
        run: |
              cat ~/.m2/settings.xml
              echo maven token: $MAVEN_TOKEN
      - name: Build
        run: |
          make clean

          make -e MVN_SETTINGS="~/.m2/settings.xml" java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get jar file path"
        working-directory: java/verticox/target
        id: "jarfile"
        run: echo JARFILE=$(ls -1 |grep -e ".jar$"|head|sed -e "s/[\t]*//") >> $GITHUB_OUTPUT
      - name: Print jarfile
        run: echo ${{ steps.jarfile.outputs.JARFILE }}
      - name: "Upload jar file as artifact"
        uses: actions/upload-artifact@v4.6.1
        with:
          name: jarfile
          path: "java/verticox/target/${{ steps.jarfile.outputs.JARFILE }}"

