# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full integration test

on:
  push:
  pull_request:
    branches: [ "main" ]
env:
  JAR_DIR: "java/verticox/target/"
  JAR_FILE: "jarfile.jar"
  $JARFILE: "java/verticox/target/jarfile.jar"
jobs:
  javabuild:
    uses: ./.github/workflows/build_java.yml
  build:
    needs: javabuild
    defaults:
      run:
        working-directory: ./mock
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download jar file
      uses: actions/download-artifact@v3
      with:
        name: ${{env.JAR_FILE}}
        path: ${{ env.JAR_DIR}}
    - uses: isbang/compose-action@v1.5.0
      with:
        compose-file: "./mock/docker-compose.yml"