name: Build and Publish
env:
  HARBOR_HOST: harbor.carrier-mu.src.surf-hosted.nl
on:
  # run it on push to the default repository branch
  push:
    branches: [ main ]
  # run it during pull request
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HARBOR_HOST }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./python
          # Note: tags has to be all lower-case
          tags: |
            ${{ env.HARBOR_HOST }}/verticox:latest
          # build on feature branches, push only on main branch
          push: True #${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}