name: Build and Publish
env:
  HARBOR_HOST: harbor.carrier-mu.src.surf-hosted.nl
  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN}}
on:
  # run it on push to the default repository branch
  push:
    branches:
      - main

jobs:
  javabuild:
    uses: ./.github/workflows/build_java.yml
    secrets: inherit
  build-and-push:
    runs-on: ubuntu-latest
    needs: javabuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: jarfile
          path: java/verticox/target
      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HARBOR_HOST }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            ${{ env.HARBOR_HOST }}/carrier/verticox:dev
          # build on feature branches, push only on main branch
          push: true
          #${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}