name: Build and Publish
env:
  HARBOR_HOST: harbor.carrier-mu.src.surf-hosted.nl
on:
  # run it on push to the default repository branch
  push:
    branches:
      - main
      - 60-add-java-to-ci

jobs:
  job1:
    uses: ./.github/workflows/build_java.yml
  build-and-push:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: test
        run: echo ${{ needs.job1.outputs.jarpath }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test other workflow

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HARBOR_HOST }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            ${{ env.HARBOR_HOST }}/carrier/verticox:dev
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}